-- ZONA DIAMANTE
-- Initial database schema

-- 1. PROFILES

create table public.profiles (
    id uuid primary key references auth.users(id),

    username text not null unique,
    display_name text,
    avatar_path text,

    points_balance integer not null default 0,
        check (points_balance >= 0),
    
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- 2. TEAMS

create table public.teams (
    id bigint generated by default as identity primary key,

    slug text not null unique,
    name text not null,
    city text,
    zone text,
    history text,

    colors jsonb,
    details jsonb,

    is_active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- 3. CARDS

create table public.cards (
    id bigint generated by default as identity primary key,

    team_id bigint not null references public.teams(id),

    slug text not null unique,
    name text not null,
    description text,
    image_path text,

    card_type text not null
        check (
            card_type in (
                'player',
                'mvp_player',
                'team',
                'mascot'
            )
        ),

    cost integer not null default 0
        check (cost >= 0),

    is_active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- 4. USER_CARDS

create table public.user_cards (
    user_id uuid not null references public.profiles(id),
    card_id bigint not null references public.cards(id),

    source text,
    unlocked_at timestamptz not null default now(),

    primary key (user_id, card_id)
);

-- 5. ACTIVITY_ATTEMPTS

create table public.activity_attempts (
    id uuid primary key default gen_random_uuid(),

    user_id uuid not null references public.profiles(id),

    activity_type text not null
        check (
            activity_type in (
                'trivia',
                'game',
                'ar'
            )
        ),

    status text not null default 'started'
        check (
            status in (
                'started',
                'completed',
                'rejected',
                'expired'
            )
        ),

    score integer,

    started_at timestamptz not null default now(),
    completed_at timestamptz,

    metadata jsonb
);

-- 6. REWARD_EVENTS

create table public.reward_events (
    id uuid primary key default gen_random_uuid(),

    user_id uuid not null references public.profiles(id),
    attempt_id uuid references public.activity_attempts(id),

    event_type text not null,

    points_delta integer not null default 0,

    card_id bigint references public.cards(id),

    idempotency_key text not null unique,

    metadata jsonb,

    created_at timestamptz not null default now()
);

-- 7. ROW LEVEL SECURITY

alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.cards enable row level security;
alter table public.user_cards enable row level security;
alter table public.activity_attempts enable row level security;
alter table public.reward_events enable row level security;